// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{
    public class ApplicationStatusViewModel
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("isSubmitted")]
        public bool IsSubmitted { get; set; }
    }

}
