// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{
    public class BiographyViewModel
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("hasImage")]
        public bool? HasImage { get; set; }

        [JsonProperty("imageRelativePath")]
        public string ImageRelativePath { get; set; }
    }

}
