// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{

    public class ClassSize
    {

        [JsonProperty("min")]
        public int Min { get; set; }

        [JsonProperty("max")]
        public int Max { get; set; }
    }

    public class TotalTime
    {

        [JsonProperty("dayOne")]
        public int DayOne { get; set; }

        [JsonProperty("dayTwo")]
        public int DayTwo { get; set; }
    }

    public class PreferredTime
    {

        [JsonProperty("dayOne")]
        public string DayOne { get; set; }

        [JsonProperty("dayTwo")]
        public string DayTwo { get; set; }
    }

    public class ExtraTime
    {

        [JsonProperty("setup")]
        public int Setup { get; set; }

        [JsonProperty("cleanup")]
        public int Cleanup { get; set; }
    }

    public class Supplies
    {

        [JsonProperty("willRequireThese")]
        public string WillRequireThese { get; set; }

        [JsonProperty("willProvideThese")]
        public string WillProvideThese { get; set; }

        [JsonProperty("willSellThese")]
        public string WillSellThese { get; set; }
    }

    public class ClassInfoViewModel
    {

        [JsonProperty("className")]
        public string ClassName { get; set; }

        [JsonProperty("classDescription")]
        public string ClassDescription { get; set; }

        [JsonProperty("classType")]
        public string ClassType { get; set; }

        [JsonProperty("feePerStudent")]
        public int FeePerStudent { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("classSize")]
        public ClassSize ClassSize { get; set; }

        [JsonProperty("skillLevel")]
        public string SkillLevel { get; set; }

        [JsonProperty("totalTime")]
        public TotalTime TotalTime { get; set; }

        [JsonProperty("preferredTime")]
        public PreferredTime PreferredTime { get; set; }

        [JsonProperty("extraTime")]
        public ExtraTime ExtraTime { get; set; }

        [JsonProperty("supplies")]
        public Supplies Supplies { get; set; }

        [JsonProperty("vendorTable")]
        public string VendorTable { get; set; }

        [JsonProperty("willNeedThisSpecialEquip")]
        public string WillNeedThisSpecialEquip { get; set; }
    }

}
