// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.CodeDom;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{

    public class AddressViewModel
    {
        public AddressViewModel()
        {
            
        }

        public AddressViewModel(AddressBindingModel bindingModel)
        {
            this.Id = bindingModel.Id;
            this.City = bindingModel.City;
            this.Street = bindingModel.Street;
            this.Province = bindingModel.Province;
            this.PostalCode = bindingModel.PostalCode;
            this.Country = bindingModel.Country;
        }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("province")]
        public string Province { get; set; }

        [JsonProperty("postalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }
    }

    public class ContactInfoViewModel
    {
        public ContactInfoViewModel()
        {
            Address = new AddressViewModel();
        }

        public ContactInfoViewModel(ContactInfoBindingModel bindingModel)
        {
            this.Id = bindingModel.Id;
            this.Name = bindingModel.Name;
            this.Address = new AddressViewModel(bindingModel.Address);
            this.PhoneDay = bindingModel.PhoneDay;
            this.PhoneCell = bindingModel.PhoneCell;
            this.BusinessName = bindingModel.BusinessName;
            this.Email = bindingModel.Email;
            this.Website = bindingModel.Website;
        }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("address")]
        public AddressViewModel Address { get; set; }

        [JsonProperty("phoneDay")]
        public string PhoneDay { get; set; }

        [JsonProperty("phoneCell")]
        public string PhoneCell { get; set; }

        [JsonProperty("businessName")]
        public string BusinessName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("website")]
        public string Website { get; set; }
    }

}
