// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{

    [Table("TeachingExperience")]
    public class TeachingExperienceBindingModel : HasAnIdentityUserFk, IBindingModel
    {
        public int Id { get; set; }

        public bool HasTaught { get; set; }

        public string YearsDecorating { get; set; }

        public string YearsTeaching { get; set; }

        public string PastConferences { get; set; }

        public string AveNumStudentsPerClass { get; set; }
    }

}
