// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace cakelove.Models
{

    public class TeachingExperienceViewModel
    {

        [JsonProperty("yearsDecorating")]
        public string YearsDecorating { get; set; }

        [JsonProperty("yearsTeaching")]
        public string YearsTeaching { get; set; }

        [JsonProperty("pastConferences")]
        public string PastConferences { get; set; }

        [JsonProperty("aveNumStudentsPerClass")]
        public string AveNumStudentsPerClass { get; set; }
    }

}
